name: pre-commit

on: push

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: pre-commit run -a
      run: |
        sudo apt install python3 -y
        pip3 install pre-commit
        pre-commit run -a
